apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-base
  namespace: test
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: go-base
    spec:
      containers:
      - name: go-base
        image: siangyeh8818/go-base-environment:v1.12
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
